server:
  address:     ":8000"
logger:
  level : "all"
  stdout: true

oss:
  allow-anonymous: true
  base-url: "https://oss.dev.lidong.xin"
  key-secrets:
    ljksdfjlksdjflksdjflksdjf: "L0asfsfsdafaScStIFqHSIP2DFV7d"
