server:
  address:     ":8000"
  clientMaxBodySize:   810241024          # 客户端最大Body上传限制大小，影响文件上传大小(Byte)。默认为8*1024*1024=8MB
logger:
  level : "all"
  stdout: true

oss:
  allowAnonymous: true
  baseUrl: "https://oss.dev.lidong.xin"
  keySecrets:
    ljksdfjlksdjflksdjflksdjf: "L0asfsfsdafaScStIFqHSIP2DFV7d"
