server:
  address:     ":8000"
logger:
  level : "all"
  stdout: true

oss:
  allowAnonymous: true
  baseUrl: "https://oss.dev.lidong.xin"
  keySecrets:
    ljksdfjlksdjflksdjflksdjf: "L0asfsfsdafaScStIFqHSIP2DFV7d"
